### PR TITLE
48 button

### PR DESCRIPTION
**Pull request by divyamrastogi**
Fixes #48
I've removed the CSS file, it wasn't necessary. You can directly use the raised button for our purpose, we don't have to overwrite any of the component-specific styles, we can use them as is.
More documentation about components: https://www.material-ui.com/#/components/raised-button
#### Checklist

- [x] I have read the Contribution & Best practices Guide and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [ ] I have added/updated necessary tests/documentation (if applicable)

Merge this request and then we'll merge your branch with the master.

### CODE REVIEW

**Comment by blenderskool** [comment]
No, I don't want to use the default Raised Button. It is not like the one which is in the design. Even if similar, default raised button won't match the other styles which will be used throughout the app. :disappointed:

**Comment by divyamrastogi** [comment]
Then you shouldn't use the Material UI button. Rather, create your own
component.

**Comment by blenderskool** [comment]
But I want the ripple and raised effect also of the default button, hence overriding that component.

Creating a custom button component with those features would make it more complicated

**Comment by divyamrastogi** [comment]
Raised button is exactly that!

**Comment by anurag-majumdar** [comment]
I think we can style the existing button and use that button component throughout the app, @blenderskool  has completed that part, it will be great with the design. The characteristics of the elements can be changed via css so it won't be an issue.

**Comment by blenderskool** [comment]
But some styles are not the same. Font weights, sizes, padding, shadows, many things are different

**Comment by blenderskool** [comment]
@divyamrastogi @anurag-majumdar Lets finish the basic working of the app. I don't think we should use the default raised button. If we use it, then we can use all the default components itself... which is **very repetitive** as of now until the new material design comes for web.

**Comment by blenderskool** [comment]
Closing this request since we should focus on finishing the development of the app.

**Pull request closed without merging**
